guardian/gu-email-renderer

- email_definitions/au.py
- email_definitions/uk.py
- email_definitions/us.py
- template/au/daily/v2015.html
- template/base_email_2015.html
- template/index.html
- template/macro/2015/layout.html
- template/macro/2015/stories.html
- template/uk/daily/v2015.html
- template/us/daily/v2015.html
This creates a parallel 2015 (Guardian convention for design changes) hierarchy.
There is a new base template and set of macros as well as a v2015 version email for each region daily email.
This means the new designs can be implemented completely without impacting the existing one.
> 2015 design: initial project structure

- email_definitions/developer.py
- mail_renderer.py
- template/index.html
Take the headline from the first item in the Film email container
> Film Today: headline of first story for testing

- data_sources/fashion.py
- email_definitions/fashion.py
- template/fashion/fashion-statement/v1.html
- template/fashion/fashion-statement/v2.html
- template/fashion/fashion-statement/v3.html
The column is due to be replaced with something else so for the moment it is being removed from the email to avoid going stale.
> Remove Ask Hadley from Fashion Statement

- email_definitions/us.py
- template/index.html
- template/macro/2015/layout.html
- template/us/daily/v2015_v3.html
...with these changes:
* change "More highlights" to "More headlines"
* make headines links to fronts (with parameter in story_trail macro)
> Add v2015_v3 US template

- template/macro/2015/stories.html
This is a quick fix for a 500 error where certain stories were missing pictures.
> Add extra thumbnail check

- email_definitions/us.py
- template/index.html
- template/macro/2015/layout.html
- template/macro/2015/stories.html
- template/us/daily/v2015_v4.html
> Adding new version of US daily email, with small images as first image.

- email_definitions/culture.py
- template/culture/film-today/v3.html
- template/culture/film-today/v4.html
- template/index.html
Creates Film Today variants for Personalisation test
> Film Today: personalisation variants

- container_api/container.py
- deduplication.py
- email_definitions/uk.py
- template/index.html
- template/uk/daily/categories.html
This creates a version of the UK email that is driven by categories on the containers.
The goal is to create a dynamic daily UK email that does not require any special programming to call out Specials and Breaking news.
> Special containers demo

- container_api/container.py
- email_definitions/au.py
- sorts/__init__.py
- sorts/au.py
- tags.py
- tests/test_sorts.py
Allows a sorting function to be passed to the containers that will allow the contents of a container to be displayed in a arbitrary way in the email.
> Containers: allow sorting function

- capi.py
- container_api/container.py
- email_definitions/au.py
- template/au/politics/v2.html
Allows additional custom parameters to be passed through to the mini-client
> CAPI: passthrough parameters

- data_source.py
- template/culture/close-up/v1.html
The quiz type has changed to a tone and the tone name is now plural.
> Close up: restore Film quizzes

- data_source.py
- email_definitions/culture.py
- template/culture/close-up/v1.html
- template/culture/close-up/v3.html
The Film Show has been cancelled so we need to stop promoting it.
> Close Up: remove the Film Show

- data_sources/__init__.py
- data_sources/mostPopular.py
- email_definitions/au.py
- ophan_calls.py
- template/au/politics/v3.html
- template/index.html
The Australia office would like to test out a new version of the Politics email. 
This template will call Ophan to get the most popular for the australia-news/australian-politics tag over the last 24 hours.
> Adds a v3 version of Australian politics daily email. 

- data_sources/au.py
- email_definitions/au.py
- template/index.html
Adds new version of Australian politics email. Similar to v3 except comment is free content to use latest result of content tagged with tone/comment and australia-news/australian-politics.
> New Australian politics format

- container_api/container.py
- data_source.py
- handlers.py
- template/au/daily/v4.html
- template/macro/layout.html
- template/uk/daily/categories.html
- template/uk/daily/nhs.html
- tests/test_mail_renderer.py
This will populate the title of an email section from the fronts tools (if the section is powered by a fronts tool container).
cc @jennysivapalan
> Pull Title overrides from the fronts tool

- template/culture/bookmarks/v1.html
Celine has requested that this is removed from bookmarks v1 also
> remove how to draw from bookmarks v1

- template/uk/daily/v2015.html
Request by Celine, this is no longer populated.
> Remove Eyewitness image of the day from UK email

- README.md
URL `http://localhost:8888/daily-email` is 404.
> Small correction in readme

- README.md
> Adds where to go find how to query the Fronts API

- data_sources/technology.py
- template/technology/zip-file.html
technology/games is dead. long live games.
> Update zip file with new games section
