guardian/gu-email-renderer

data_source.py

To support the new designs we need to include tone and type for all content.
This isn't particularly elegant but the necessary data comes through.

Datastores: default show tags

---

data_source.py
data_sources/technology.py
data_sources/us.py

The datasources for the US email should be updated with the correct CAPI parameters to allow them to function.
The Mohawk version puts them in the defaults which might cause the other emails to blow up.

2015 design: change US datasources

---

cron.yaml
data_source.py
email_definitions/us.py
template/uk/daily/v2015.html
template/us/daily/v2015.html

The PR had a few issues that would cause problems for other emails.
In addition the UK email was crashing due to the presence of Eyewitness
There were also a few merge elements that were historic and which we didn't want to reactivate.

2015 design: cleanup Mohawk merge

---

template/base_email_2015.html
template/macro/2015/layout.html

Exact Target wrappings were removing the style assigned to the text in the button.

Inlining style for the plus button

---

email_definitions/us.py
template/index.html
template/macro/2015/layout.html
template/macro/2015/stories.html
template/us/daily/v2015_v2.html

This implements a version of the email that removes kickers to provide a split test option.
Manual testing suggests that kickers negatively impact click-through.

US: 2015 design: no kickers version

---

template/macro/2015/layout.html
template/us/daily/v2015_v3.html

Two tweaks to the US template: 
* Shorten "most shared" button text
* Ensure the header title links aren't underlined (which was happening in gmail)

US template tweaks

---

handlers.py
template/au/morning/v1.html
template/macro/2015/layout.html
template/macro/2015/stories.html
template/macro/layout.html
template_filters.py

This is a slight change to the `largest_image` filter to allow a hard limit (width) to be passed in. If it's there, only images that are below that width will make it through the filter.
Should fix a bug where some very big images have been appearing in the 2015 template:

Add image width capping

---

template/components/eyewitness.html
template/macro/layout.html

This image is currently coming through at 5000px so we should use the filter to limit the size.

Add max_width param to eyewitness image

---

email_definitions/uk.py
template/index.html
template/uk/daily/nhs.html

While the NHS campaign is running this provides a temporary email that can be used instead of the regular UK morning mail.

NHS Special: temporary UK email

---

email_definitions/culture.py
template/culture/bookmarks/v2.html
template/index.html

Talking Points is now drawn from the relevant container and more stories are drawn from it.
The old Talking Points section has now been more accurately named Book Blogs.
I've reviewed this with Sian Cain and we'll run a split test for the next email.

Bookmarks: v2: Talking Points update

---

template_filters.py

The previous code would blow up if there were no images that met the width restriction. This version provides a failure mode where if the content has images the macro will choose the smallest width if no images are found below the required width. This seems like the simplest way to have the email be generated without manual intervention.

Macros: Images: image width filter should fail gracefully

---

data_source.py

DAPI might return an empty list of stories being discussed. Currently this blows up the email but this change logs the fact that the result is empty but should allow the email to still be generated.

Comments: survive empty DAPI responses

---

capi.py
container_api/container.py
email_definitions/uk.py

This simplified version of the CAPI item reader was being used inside the container API client but I've broken it out to simplify maintainence and also to avoid bloating the container functionality.

CAPI: breakout mini-client

---

deduplication.py

Where a content item cannot be resolved it should be ignored for the purpose of deduping.
This is guard fix but it might be better to elimnate None results from the source that generates them.

Deduplication: strip failed reads

---

data_source.py
tags.py
test_runner.py
tests/test_data_sources.py
tests/test_tags.py

As part of the rework of the Australian Politics newsletter we want to be able to say whether a piece of content has the Australia Politics tag or not.
I also discovered that the test runner was broken for CI in that it wasn't returning an error status and therefore we had been breaking a number of the tests without realising it. This should be fixed now, along with the tests that had been broken for a while.

Tags: detect presence of a tag

---

email_definitions/uk.py
template/uk/daily/categories.html

A couple of changes based on editorial requests:
> - Top stories query expanded to contain 5 stories 
> - 'Editors picks' subheader to be renamed to 'Headlines'

Categories fixes

---

email_definitions/au.py
template/au/daily/v4.html
template/index.html

This introduces a version of the Australian email that matches that of the UK categories email.

Australia: Daily email: front tag version

---

template/culture/bookmarks/v2.html

requested as 'how to draw' is no longer maintained
there are other references to 'how to draw' which are still in place, these can be removed if needed

remove how to draw from bookmarks v2

---

handlers.py

`oas.theguardian.com` went away and broke a number of mails. This PR disables the calls to it whilst we investigate whether it was still required

Remove calls to decommisioned ad server

---

data_source.py
data_sources/technology.py
handlers.py
template/macro/layout.html
template_filters.py
util.py

This change fixes the email renderer for video atoms. Currently they are broken due to not having an elements block. 
I've moved some of the logic that was previously in the template out into a template filter which hopefully makes it a bit more readable.

Make the template (just zip file currently) work for video atoms.

---

README.md
configuration.py
handlers.py
template/base_email.html
tests/test_mail_renderer.py

In the run up to Garnett we need to change emails to fit with the new branding. Since the email renderer is deprecated for all intents and purposes this PR adds a `showHeaderAndFooter` query parameter that removes the old branded header and footer. The emails are scraped into a marketing tool anyway that will add correctly branded ones.
The change caused two test failures due to the request not being mocked out correctly. I have ignored rather than fixed them since I can't get the test runner to work locally with the latest version of the app engine SDK. Again, this renderer should be deprecated and eventually switched off.
I've also made a small change to Configuration to make it easier to run this guy up in dev. See the [comment …

Make header and footer optional

---

handlers.py
template/base_email.html
template/index.html
template/index.jan2018.html
tests/test_mail_renderer.py

The decision has been made to update the logos and remove the old social links at the bottom of the  mails. So that's what this PR does.
I've also reverted #54 (query param to disable header and footer) since it's no longer required. We also now have access to the spreadsheet showing what emails are still based on this renderer so I've updated the front page accordingly.
In case we've lost any links we actually need, the previous front page can be seen by sticking `?showAll=true` on the end.

Garnett email renderer updates

---

template/index.html

Remove US opinion as they are now using the frontend email support. Put back two headline links that are still in use.
The rationale is that Celine is going on sabbatical soon and it's best for the page to reflect the reality of which bits are still in use to avoid confusing her cover.
You can still see all of the links with a query parameter: http://gu-email-renderer.appspot.com/?showAll=true.

Update links on front page
